{% set version = "1.2.4" %}

package:
  name: h3-pyspark
  version: {{ version }}

source:
  url: https://github.com/kevinschaich/h3-pyspark/archive/refs/tags/{{ version }}.tar.gz
  sha256: 72173dc81c8fe67c9b64d14f72bbaa9fd699c72e396ad6232f717260cca5c91e

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - pytest
    - black
  host:
    - pip
    - python >=3.6
  run:
    - python >=3.6
    - pyspark
    - h3-py
    - shapely

test:
  imports:
    - h3_pyspark

about:
  home: https://github.com/kevinschaich/h3-pyspark
  summary: PySpark bindings for H3, a hierarchical hexagonal geospatial indexing system
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  dev_url: https://github.com/kevinschaich/h3-pyspark
  doc_url: https://github.com/kevinschaich/h3-pyspark

extra:
  recipe-maintainers:
    - kevinschaich
